USE db;

-- Users table
CREATE TABLE UserAccounts (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(100) NOT NULL UNIQUE,
	username VARCHAR(100) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	enable_2FA BOOLEAN DEFAULT FALSE,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Players table
CREATE TABLE Players (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	pseudonym VARCHAR(50) NOT NULL,
	description TEXT,
	coins INT DEFAULT 0,
	avatar_url VARCHAR(255),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES UserAccounts(id) ON DELETE CASCADE
);

-- Matches table
CREATE TABLE Matches (
	id INT AUTO_INCREMENT PRIMARY KEY,
	match_name VARCHAR(100),
	start_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	end_time DATETIME
);

-- PlayerStats table
CREATE TABLE PlayerStats (
	id INT AUTO_INCREMENT PRIMARY KEY,
	player_id INT NOT NULL,
	match_id INT NOT NULL,
	chrono INT DEFAULT 0,
	position INT,
	eliminated BOOLEAN DEFAULT FALSE,
	FOREIGN KEY (player_id) REFERENCES Players(id) ON DELETE CASCADE,
	FOREIGN KEY (match_id) REFERENCES Matches(id) ON DELETE CASCADE
);

-- Items table
CREATE TABLE Items (
	id INT AUTO_INCREMENT PRIMARY KEY,
	player_id INT NOT NULL,
	item_name VARCHAR(100) NOT NULL,
	item_type VARCHAR(50),
	acquired_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (player_id) REFERENCES Players(id) ON DELETE CASCADE
);

-- Leaderboard table
CREATE TABLE Leaderboard (
	id INT AUTO_INCREMENT PRIMARY KEY,
	player_id INT NOT NULL,
	total_score INT DEFAULT 0,
	global_rank INT,
	last_update DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (player_id) REFERENCES Players(id) ON DELETE CASCADE
);
