USE db;

-- Users table
CREATE TABLE userAccounts (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(100) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Players table
CREATE TABLE players (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	pseudonym VARCHAR(50) NOT NULL,
	bio TEXT,
	coins INT DEFAULT 0,
	avatar_url VARCHAR(255),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES userAccounts(id) ON DELETE CASCADE
);

-- Games table
CREATE TABLE games (
	id INT AUTO_INCREMENT PRIMARY KEY,
	mode VARCHAR(100),
	start_time DATETIME DEFAULT CURRENT_TIMESTAMP,
	end_time DATETIME
);

-- PlayerStats table
CREATE TABLE playerStats (
	id INT AUTO_INCREMENT PRIMARY KEY,
	player_id INT NOT NULL,
	game_id INT NOT NULL,
	chrono INT DEFAULT 0,
	position INT,
	eliminated BOOLEAN,
	FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
	FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);

-- Items table
CREATE TABLE items (
	id INT AUTO_INCREMENT PRIMARY KEY,
	player_id INT NOT NULL,
	item_name VARCHAR(100) NOT NULL,
	item_type VARCHAR(50),
	acquired_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);

-- Leaderboard table
CREATE TABLE leaderboard (
	id INT AUTO_INCREMENT PRIMARY KEY,
	player_id INT NOT NULL,
	total_score INT DEFAULT 0,
	global_rank INT,
	last_update DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);
